name: tweleve_ace
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1
  # sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^7.0.0
  http: ^1.4.0
  file_picker: ^10.1.9
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  flutter_dotenv: ^5.2.1
  font_awesome_flutter: ^10.8.0 
  cached_network_image: ^3.4.1 
  # skeletonizer: ^2.0.1
  flutter_native_splash: ^2.4.6
  get_it: ^8.0.3
  injectable: ^2.5.0
  go_router: ^15.1.2
  dartz: ^0.10.1
  intl: ^0.20.2

flutter_native_splash:
  android: true
  ios: true
  web: true

  color: "#5fb670"
  # background_image: "assets/git_images/empty.png"
  image: "assets/images/splash.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/splash.png
    - .env

  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
    - family: Blanka
      fonts:
        - asset: assets/fonts/Blanka-Regular.otf